# Generated by Django 4.0 on 2022-01-26 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.TextField(max_length=1500)),
                ('ContactNo', models.CharField(max_length=250)),
                ('Status', models.BooleanField(default=False)),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataModels',
            fields=[
                ('ModalId', models.AutoField(primary_key=True, serialize=False)),
                ('ModalTitle', models.CharField(max_length=250)),
                ('ModalDescription', models.TextField(max_length=2500)),
                ('ModalThumbnail', models.ImageField(upload_to='modal/')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('AgencyName', models.CharField(max_length=250)),
                ('Username', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.TextField(max_length=1500)),
                ('ContactNo', models.CharField(max_length=250)),
                ('Address', models.TextField(max_length=550)),
                ('Status', models.CharField(default='pending', max_length=100)),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WebisteModal',
            fields=[
                ('WebsiteId', models.AutoField(primary_key=True, serialize=False)),
                ('WebsiteTitle', models.CharField(default='Anti Medi Care', max_length=250)),
                ('WebsiteDescription', models.TextField(max_length=500)),
                ('WebsiteEmail', models.CharField(default='admin@fyp.com', max_length=250)),
                ('WebsiteContactNo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('LocationTitle', models.CharField(max_length=250)),
                ('Lititude', models.FloatField(default=0)),
                ('Longitude', models.FloatField(default=0)),
                ('ContactNo', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=2500)),
                ('Address', models.CharField(max_length=250)),
                ('WebsiteLink', models.CharField(max_length=250)),
                ('Status', models.CharField(default='pending', max_length=100)),
                ('ModalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datamodels')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
        ),
    ]
