# Generated by Django 3.2.10 on 2021-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebisteModal',
            fields=[
                ('WebsiteId', models.AutoField(primary_key=True, serialize=False)),
                ('WebsiteTitle', models.CharField(default='Anti Medi Care', max_length=250)),
                ('WebsiteDescription', models.TextField(max_length=500)),
                ('WebsiteEmail', models.CharField(default='admin@fyp.com', max_length=250)),
                ('WebsiteContactNo', models.CharField(max_length=200)),
            ],
        ),
    ]
