# Generated by Django 4.0 on 2021-12-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webistemodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='Status',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Status',
            field=models.TextField(default='False'),
        ),
    ]
