# Generated by Django 4.0 on 2022-02-05 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usermodel_vendormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('EmailName', models.CharField(max_length=200)),
                ('ContactNo', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=250)),
                ('Password', models.TextField(max_length=2000)),
                ('Token', models.CharField(max_length=100)),
                ('Status', models.CharField(default='pending', max_length=100)),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='vendormodel',
            old_name='UserId',
            new_name='VendorId',
        ),
        migrations.AddField(
            model_name='adminmodel',
            name='Token',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
