# Generated by Django 4.0 on 2022-02-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usermodel_rename_userid_vendormodel_vendorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='EmailName',
            new_name='Email',
        ),
    ]
