# Generated by Django 4.0 on 2021-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_locationmodel_status_alter_usermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
