# Generated by Django 4.0 on 2022-02-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_emailname_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTitle', models.CharField(max_length=250)),
                ('Lititude', models.FloatField(default=0)),
                ('Longitude', models.FloatField(default=0)),
                ('ContactNo', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=2500)),
                ('Address', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('qty', models.IntegerField(default=0)),
                ('WebsiteLink', models.CharField(max_length=250)),
                ('Status', models.CharField(default='pending', max_length=100)),
                ('ModalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datamodels')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendormodel')),
            ],
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
    ]
