# Generated by Django 4.0 on 2022-02-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='Product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.productmodel'),
        ),
    ]
