# Generated by Django 4.0 on 2022-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ordermodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Qty',
            field=models.IntegerField(),
        ),
    ]
